version: 2
jobs:
  
  netcore2_with_tests:
    parallelism: 4
    docker:
      - image: microsoft/dotnet:3.0-sdk
    environment:
        FrameworkPathOverride: '/usr/lib/mono/4.5/'
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout

      - run: |
          apt-get update
          apt-get install mono-devel mono-utils -y

      - run: dotnet restore
      
      - run:
          name: Build Sample project against netstandard2.0
          command: |
            dotnet build src/dotnet-ildasm.Sample/dotnet-ildasm.Sample.csproj -f netstandard2.0 -c Release
            dotnet build src/dotnet-ildasm.Sample/dotnet-ildasm.Sample.csproj -f net45 -c Release

      - run:
          name: Build ildasm project for netcore 2.2
          command: |
            dotnet build src/dotnet-ildasm/dotnet-ildasm.csproj -f netcoreapp2.2 -c Release

      - run:
          name: Build ildasm project for netcore 2.1
          command: |
            dotnet build src/dotnet-ildasm/dotnet-ildasm.csproj -f netcoreapp2.1 -c Release

      - run:
          name: Executing dotnet core ildasm against netstandard2.0 library
          command: |
            dotnet run --framework netcoreapp2.2 --project src/dotnet-ildasm/dotnet-ildasm.csproj src/dotnet-ildasm.Sample/bin/Release/netstandard2.0/dotnet-ildasm.Sample.dll -o /root/project/netcore22_netstandard20.il

      - run:
          name: Reassemble library based from IL
          command: |
            cd /usr/lib/mono/4.5/
            ilasm /root/project/netcore22_netstandard20.il /dll /output:netcore2_netstandard20.dll
  


  netcore3_with_tests:
    parallelism: 4
    docker:
      - image: microsoft/dotnet:3.0-sdk
    environment:
        FrameworkPathOverride: '/usr/lib/mono/4.5/'
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout

      - run: |
          apt-get update
          apt-get install mono-devel mono-utils -y

      - run: dotnet restore
      
      - run:
          name: Build Sample project against netstandard2.0
          command: |
            dotnet build src/dotnet-ildasm.Sample/dotnet-ildasm.Sample.csproj -f netstandard2.0 -c Release

      - run:
          name: Build ildasm project for netcore 3.0
          command: |
            dotnet build src/dotnet-ildasm/dotnet-ildasm.csproj -f netcoreapp3.0 -c Release

      - run:
          name: Executing dotnet core ildasm against netstandard3.0 library
          command: |
            dotnet run --framework netcoreapp3.0 --project src/dotnet-ildasm/dotnet-ildasm.csproj /root/project/src/dotnet-ildasm.Sample/bin/Release/netstandard2.0/dotnet-ildasm.Sample.dll -o /root/project/netcore3_netstandard20.il

      - run:
          name: Reassemble library based from IL
          command: |
            cd /usr/lib/mono/4.5/
            ilasm /root/project/netcore3_netstandard20.il /dll /output:netcore3_netstandard20.dll



workflows:
  version: 2
  build_and_test:
    jobs:
      - netcore2_with_tests
      - netcore3_with_tests