version: 2
jobs:
  
  netcore1_1_with_tests:
    docker:
      - image: microsoft/dotnet:1.1-sdk
    environment:
      RUN_MONO_TESTS: 1
      RUN_REASSEMBLE_TESTS: 1
      FrameworkPathOverride: "/usr/lib/mono/4.5/"
    steps:
      - checkout
      - run: |
          chmod +x build.sh
          chmod +x run-cross-checks.sh
          dotnet restore
          apt-get update
          apt-get install mono-utils -y

      - run: ./build.sh -c Release
      - run: ./run-cross-checks.sh

  netcore2_0:
    docker:
      - image: microsoft/dotnet:2.0-sdk
    environment:
      BUILD_NETCORE_20: 1
    steps:
      - checkout
      - run: |
          chmod +x build.sh
          dotnet restore

      - run: ./build.sh -c Release

  netcore2_1_with_tests:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout

      - run: |
          apt-get update
          apt-get install mono-devel mono-utils -y

      - run: |
          dotnet restore
          dotnet build src/dotnet-ildasm.Sample/dotnet-ildasm.Sample.csproj -f netstandard1.6 -c Release

      - run:
          name: Build ildasm project
          command: dotnet build src/dotnet-ildasm/dotnet-ildasm.csproj -f netcoreapp2.1 -c Release

      - run:
          name: Executing dotnet core ildasm against netstandard1.6 library
          command: dotnet run --framework netcoreapp2.1 --project src/dotnet-ildasm/dotnet-ildasm.csproj src/dotnet-ildasm.Sample/bin/Release/netstandard1.6/dotnet-ildasm.Sample.dll -o netcore_netstandard16.il

      - run:
          name: Reassemble library based on IL
          command: |
            cd /usr/lib/mono/4.5/
            ilasm.exe netcore_netstandard16.il /dll /output:netcore_netstandard16.dll

workflows:
  version: 2
  build_and_test:
    jobs:
      - netcore2_1_with_tests