version: 2
jobs:
  
  netcore1_1_with_tests:
    docker:
      - image: microsoft/dotnet:1.1-sdk
    environment:
      RUN_MONO_TESTS: 1
      RUN_REASSEMBLE_TESTS: 1
      FrameworkPathOverride: "/usr/lib/mono/4.5/"
    steps:
      - checkout
      - run: |
          chmod +x build.sh
          chmod +x run-cross-checks.sh
          dotnet restore
          apt-get update
          apt-get install mono-utils -y

      - run: ./build.sh -c Release
      - run: ./run-cross-checks.sh

  netcore2_0:
    docker:
      - image: microsoft/dotnet:2.0-sdk
    environment:
      BUILD_NETCORE_20: 1
    steps:
      - checkout
      - run: |
          chmod +x build.sh
          dotnet restore

      - run: ./build.sh -c Release

  netcore2_1_with_tests:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    environment:
      BUILD_NETCORE_21: 1
      RUN_MONO_TESTS: 1
      RUN_REASSEMBLE_TESTS: 1
      FrameworkPathOverride: "/usr/lib/mono/4.5/"
    steps:
      - checkout
      - run: |
          chmod +x build.sh
          chmod +x run-cross-checks.sh
          dotnet restore
          apt-get update
          apt-get install mono-utils -y
          ls /usr/lib/mono

      - run: ./build.sh -c Release
      - run: ./run-cross-checks.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - netcore2_1_with_tests